[theme]
primaryColor = "#EF4444"
backgroundColor = "#0B0F1A"
secondaryBackgroundColor = "#161E2E"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
displayStatics = "always"

[ui]
hideTopBar = true
